name: test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - uses: purcell/setup-emacs@master
        with:
          version: '29.4'
      - uses: cask/setup-cask@master
        with:
          version: '0.8.8'
      - name: Setup packages
        run: make setup
      - name: Run test
        run: UNDERCOVER_FORCE=t make test
      - name: Run lint
        run: make lint
      - name: Reformat coverage report
        run: |
          jq '.["undercover.el"]
             | del(.timestamp)
             | map_values(map_values([null]+.))
          ' simplecov.json > coverage-final.json
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage-final.json
          flags: undercover
          name: simplecov
